name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: 'Ignacio'  # Define tu variable de entorno aquí

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and generate coverage report
        run: ./gradlew test jacocoTestReport

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Upload coverage report to GitHub as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      - name: Upload SpotBugs report to GitHub as artifact
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/main.html  # Ruta al reporte HTML de SpotBugs

  publish:
    runs-on: ubuntu-latest
    needs: build  # Este job se ejecuta después del job 'build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.NAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}