name: Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama donde deseas que se publique automáticamente

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Usa Temurin JDK
          java-version: '19'

      - name: Build and publish package
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
